import math

def calculate_heating_load(data):
    # Simple heating load
    q_walls = data['u_walls'] * data['area_walls'] * (data['t_indoor'] - data['t_outdoor'])
    q_windows = data['u_windows'] * data['area_windows'] * (data['t_indoor'] - data['t_outdoor'])
    q_roof = data['u_roof'] * data['area_roof'] * (data['t_indoor'] - data['t_outdoor'])
    q_conduction = q_walls + q_windows + q_roof

    cfm = (data['volume'] * data['ach']) / 60
    q_infil = 1.08 * cfm * (data['t_indoor'] - data['t_outdoor'])

    total = q_conduction + q_infil
    return {
        'total_btu_hr': round(total),
        'cfm': round(cfm, 1)
    }


def calculate_cooling_load(data):
    # Simple cooling load
    q_walls = data['u_walls'] * data['area_walls'] * 25
    q_roof = data['u_roof'] * data['area_roof'] * 40
    q_windows = data['u_windows'] * data['area_windows'] * 12
    q_solar = data['area_windows'] * 140   # simplified

    cfm = (data['volume'] * data.get('ach', 0.5)) / 60
    q_inf_s = 1.08 * cfm * (data['t_outdoor'] - data['t_indoor'])
    q_inf_l = 0.68 * cfm * 30

    q_people = data.get('occupants', 0) * 380
    q_lights = data.get('lighting_watts', 0) * 3.41

    sensible = q_walls + q_roof + q_windows + q_solar + q_inf_s + q_people + q_lights
    latent = q_inf_l
    total = sensible + latent

    return {
        'total_btu_hr': round(total),
        'tons': round(total / 12000, 2),
        'cfm': round(sensible / (1.08 * 20))
    }
from fpdf import FPDF
from datetime import datetime

def generate_pdf_report(data: dict, result: dict, mode: str) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "HVAC Load Calculation Report", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 8, f"Mode: {mode}", ln=True)
    pdf.ln(5)

    # Input Summary
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Input Data:", ln=True)
    pdf.set_font("Arial", "", 11)
    for key, value in data.items():
        if key not in ['mode']:
            pdf.cell(0, 6, f"• {key.replace('_', ' ').title()}: {value}", ln=True)
    pdf.ln(8)

    # Results
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Results:", ln=True)
    pdf.set_font("Arial", "", 11)

    if "Heating" in mode:
        pdf.cell(0, 6, f"Total Heating Load: {result['total_btu_hr']} BTU/hr", ln=True)
        pdf.cell(0, 6, f"Recommended Airflow: {result['cfm']} CFM", ln=True)
    else:
        pdf.cell(0, 6, f"Total Cooling Load: {result['total_btu_hr']} BTU/hr", ln=True)
        pdf.cell(0, 6, f"Tons: {result['tons']} Tons", ln=True)
        pdf.cell(0, 6, f"Supply Airflow: {result['cfm']} CFM", ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 8, "Generated by HVAC Telegram Bot", ln=True, align="C")

    filename = f"hvac_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    pdf.output(filename)
    return filename