from fpdf import FPDF
from datetime import datetime

def calculate_heating_load(data: dict) -> dict:
    q_walls = data.get('u_walls', 0.06) * data.get('area_walls', 0) * (data['t_indoor'] - data['t_outdoor'])
    q_windows = data.get('u_windows', 0.35) * data.get('area_windows', 0) * (data['t_indoor'] - data['t_outdoor'])
    q_roof = data.get('u_roof', 0.04) * data.get('area_roof', 0) * (data['t_indoor'] - data['t_outdoor'])
    q_conduction = q_walls + q_windows + q_roof

    cfm = (data.get('volume', 0) * data.get('ach', 0.5)) / 60
    q_infil = 1.08 * cfm * (data['t_indoor'] - data['t_outdoor'])

    total = q_conduction + q_infil
    return {
        'total_btu_hr': round(total),
        'cfm': round(cfm, 1)
    }


def calculate_cooling_load(data: dict) -> dict:
    q_walls = data.get('u_walls', 0.06) * data.get('area_walls', 0) * 25
    q_roof = data.get('u_roof', 0.04) * data.get('area_roof', 0) * 40
    q_windows = data.get('u_windows', 0.35) * data.get('area_windows', 0) * 12
    q_solar = data.get('area_windows', 0) * 140

    cfm = (data.get('volume', 0) * data.get('ach', 0.5)) / 60
    delta_t = data['t_outdoor'] - data['t_indoor']
    q_inf_s = 1.08 * cfm * delta_t
    q_inf_l = 0.68 * cfm * 30

    q_people = data.get('occupants', 0) * 380
    q_lights = data.get('lighting_watts', 0) * 3.41

    sensible = q_walls + q_roof + q_windows + q_solar + q_inf_s + q_people + q_lights
    total = sensible + q_inf_l

    return {
        'total_btu_hr': round(total),
        'tons': round(total / 12000, 2),
        'cfm': round(sensible / (1.08 * 20))
    }


def generate_pdf_report(data: dict, result: dict, mode: str) -> str:
    """Clean PDF without emojis"""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "HVAC LOAD CALCULATION REPORT", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 8, f"Type: {mode}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "INPUT PARAMETERS", ln=True)
    pdf.set_font("Arial", "", 11)
    for key, value in data.items():
        if key != "mode":
            pdf.cell(0, 6, f"• {key.replace('_', ' ').title()}: {value}", ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "RESULTS", ln=True)
    pdf.set_font("Arial", "", 11)

    if "Heating" in mode:
        pdf.cell(0, 8, f"Total Heating Load: {result.get('total_btu_hr')} BTU/hr", ln=True)
        pdf.cell(0, 8, f"Airflow: {result.get('cfm')} CFM", ln=True)
    else:
        pdf.cell(0, 8, f"Total Cooling Load: {result.get('total_btu_hr')} BTU/hr", ln=True)
        pdf.cell(0, 8, f"Tons: {result.get('tons')} Tons", ln=True)
        pdf.cell(0, 8, f"Airflow: {result.get('cfm')} CFM", ln=True)

    pdf.ln(20)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 8, "Generated by HVAC Telegram Bot", ln=True, align="C")

    filename = f"hvac_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    pdf.output(filename)
    return filename